<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rounds', 'doctrine');

/**
 * BaseRounds
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property integer $rank
 * @property string $name
 * @property string $cellname
 * 
 * @method string  getId()       Returns the current record's "id" value
 * @method integer getRank()     Returns the current record's "rank" value
 * @method string  getName()     Returns the current record's "name" value
 * @method string  getCellname() Returns the current record's "cellname" value
 * @method Rounds  setId()       Sets the current record's "id" value
 * @method Rounds  setRank()     Sets the current record's "rank" value
 * @method Rounds  setName()     Sets the current record's "name" value
 * @method Rounds  setCellname() Sets the current record's "cellname" value
 * 
 * @package    iwca
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRounds extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Rounds');
        $this->hasColumn('id', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('rank', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('cellname', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}