<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Persons', 'doctrine');

/**
 * BasePersons
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property integer $subid
 * @property string $name
 * @property string $countryid
 * @property string $gender
 * 
 * @method string  getId()        Returns the current record's "id" value
 * @method integer getSubid()     Returns the current record's "subid" value
 * @method string  getName()      Returns the current record's "name" value
 * @method string  getCountryid() Returns the current record's "countryid" value
 * @method string  getGender()    Returns the current record's "gender" value
 * @method Persons setId()        Sets the current record's "id" value
 * @method Persons setSubid()     Sets the current record's "subid" value
 * @method Persons setName()      Sets the current record's "name" value
 * @method Persons setCountryid() Sets the current record's "countryid" value
 * @method Persons setGender()    Sets the current record's "gender" value
 * 
 * @package    iwca
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersons extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Persons');
        $this->hasColumn('id', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('subid', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('name', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('countryid', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('gender', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}