<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RanksAll', 'doctrine');

/**
 * BaseRanksAll
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $personid
 * @property integer $singlerank
 * @property integer $averagerank
 * @property integer $singlesum
 * @property integer $averagesum
 * 
 * @method integer  getId()          Returns the current record's "id" value
 * @method string   getPersonid()    Returns the current record's "personid" value
 * @method integer  getSinglerank()  Returns the current record's "singlerank" value
 * @method integer  getAveragerank() Returns the current record's "averagerank" value
 * @method integer  getSinglesum()   Returns the current record's "singlesum" value
 * @method integer  getAveragesum()  Returns the current record's "averagesum" value
 * @method RanksAll setId()          Sets the current record's "id" value
 * @method RanksAll setPersonid()    Sets the current record's "personid" value
 * @method RanksAll setSinglerank()  Sets the current record's "singlerank" value
 * @method RanksAll setAveragerank() Sets the current record's "averagerank" value
 * @method RanksAll setSinglesum()   Sets the current record's "singlesum" value
 * @method RanksAll setAveragesum()  Sets the current record's "averagesum" value
 * 
 * @package    iwca
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRanksAll extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('RanksAll');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('personid', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('singlerank', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('averagerank', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('singlesum', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('averagesum', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}