<?php

/**
 * AveragesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AveragesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AveragesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Averages');
    }
}