<?php

/**
 * AveragesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AveragesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AveragesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Averages');
    }

    /**
     * アベレージランキングを取得。
     * @param type    0:Ranking 1:Result
     * @param eventId イベント
     * @param region  地域
     * @param years   年
     * @param gender  性別
     * @return array  結果
     */
    public function getRanking($type, $eventId, $region, $years, $gender, $limit, $offset)
    {
      $query = $this->createQuery();
      $q->select('average, personid, eventid, personname, value1, value2, value3, value4, value5, personcountryid, competitionname');
      $query->andWhere('eventid = ?', $eventId);

      if ($region && $region != sfConfig::get('app_region_default')) {
        Query::region(&$query, $region);
      }

      if ($years) {
        Query::years(&$query, $years);
      }

      if ($gender) {
        Query::gender(&$query, $gender);
      }

      if ($type) {
        Query::groupBy(&$query, 'personId');
      }

      if ($limit) {
        Query::limit(&$query, $limit);
      }

      if ($offset) {
        Query::offset(&$query, $offset);
      }

      $query->orderBy('average, personname ASC');
      $query->useResultCache(true);

      $results = $query->fetchArray();

      $query->free();
      unset($q);

      return $results;
    }
}
