<?php

/**
 * CompetitionsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompetitionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompetitionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Competitions');
    }

    /**
     * 大会リストを取得する
     * @params eventId イベントID
     * @params region 地域
     * @params years 年
     * @parasm 検索文字列
     * @return 大会リスト
     */
    public function getCompetitionList($eventId, $region, $years, $keyword)
    {
      $query = $this->createQuery();
      $query->select('cellname, cityname, countryid, year, month, day, endmonth, endday');

      if ($eventId != 'All') {
        Query::competitionEvent(&$query, $eventId);
      }

      if ($region && $region != 'World') {
        Query::region(&$query, $region);
      }

      if ($years && $years != 'All') {
        Query::years(&$query, $years);
      }

      if ($keyword) {
        Query::keyword(&$query, $keyword);
      }

      $query->useResultCache(true);

      $results = $query->fetchArray();
      $query->free();
      unset($query);

      return $results;
    }
}
