<?php

/**
 * CompetitionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompetitionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompetitionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Competitions');
    }
}