<?php

/**
 * ContinentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContinentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContinentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Continents');
    }
}