<?php

/**
 * FormatsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormatsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormatsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Formats');
    }
}