<?php

/**
 * PersonsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonsTable
     */
    public static function getInstance()
    {
      return Doctrine_Core::getTable('Persons');
    }

    public function getPerson($id)
    {
      $query = $this->createQuery();
      $query->where('id = ?', $id);

      $query->useResultCache(true);
      $results = $query->fetchOne();

      $query->free();
      unset($query);

      return $results;
    }

    public function getPersons($region, $keyword, $type)
    {
      $query = $this->createQuery();

      if ($keyword) {
        Query::searchName(&$query, $keyword, $type);
      } else {
        $query->orderBy('name');
      }

      if ($region) {
        Query::personRegion(&$query, $region);
      }

      $query->useResultCache(true);
      $results = $query->fetchArray();

      $query->free();
      unset($query);

      return $results;
    }
}
