<?php

/**
 * PersonsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Persons');
    }
}