<?php

/**
 * RanksAverageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RanksAverageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RanksAverageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RanksAverage');
    }
}