<?php

/**
 * RanksAllTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RanksAllTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RanksAllTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RanksAll');
    }
}