<?php

/**
 * RanksSingleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RanksSingleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RanksSingleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RanksSingle');
    }
}