<?php

/**
 * ResultsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResultsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResultsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Results');
    }
}