<?php

/**
 * RoundsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoundsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoundsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rounds');
    }
}