<?php

/**
 * SinglesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SinglesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SinglesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Singles');
    }
}