# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
all:
  wca_official_result_url: 'http://www.worldcubeassociation.org/results/'
  wca_official_events_number: 18

  most_old_year: 1982
  recently_old_year: 2003
  now_year: 2014

  cubecomps:
    list_url: 'http://m.cubecomps.com/competitions.json'
    event_url: 'http://m.cubecomps.com/competitions/%s/events'

  name:
    continents: { 0: Africa, 1: Asia, 2: Europe, 3: North America, 4: Oceania, 5: South America }
    record:     { Africa: AfR, Asia: AsR, Oceania: OcR, Europe: ER, North America: NAR, South America: SAR }

  record:
    id: ['AfR', 'AsR', 'OcR', 'ER', 'NAR', 'SAR']

  region:
    default: World

  round:
    id:
     0:      { name: Qualification Round }
     d:      { name: Combined First Round }
     1:      { name: First Round }
     2:      { name: Second Round }
     3:      { name: Semi Final }
     b:      { name: B Final }
     c:      { name: Combined Final }
     f:      { name: Final }

  # 逆順用
  round_reverse:
    id:
     f:      { name: Final }
     c:      { name: Combined Final }
     b:      { name: B Final }
     3:      { name: Semi Final }
     2:      { name: Second Round }
     1:      { name: First Round }
     d:      { name: Combined First Round }
     0:      { name: Qualification Round }

  format:
    id:
     1:      { name: Best of 1 }
     2:      { name: Best of 2 }
     3:      { name: Best of 3 }
     a:      { name: Average of 5 }
     m:      { name: Mean of 3 }

  event:
    id:
      333:    { name: 'Rubik''s Cube',                       format: 'Average', cellname: 'Rubik''s Cube' }
      444:    { name: '4x4 Cube',                            format: 'Average', cellname: '4x4 Cube' }
      555:    { name: '5x5 Cube',                            format: 'Average', cellname: '5x5 Cube' }
      222:    { name: '2x2 Cube',                            format: 'Average', cellname: '2x2 Cube' }
      333bf:  { name: 'Rubik''s Cube: Blindfolded',          format: 'Average', cellname: '3x3 Blindfolded' }
      333oh:  { name: 'Rubik''s Cube: One-handed',           format: 'Average', cellname: '3x3 One-handed' }
      333fm:  { name: 'Rubik''s Cube: Fewest moves',         format: 'Average', cellname: '3x3 Fewest moves' }
      333ft:  { name: 'Rubik''s Cube: With feet',            format: 'Average', cellname: '3x3 With feet' }
      minx:   { name: 'Megaminx',                            format: 'Average', cellname: 'Megaminx' }
      pyram:  { name: 'Pyraminx',                            format: 'Average', cellname: 'Pyraminx' }
      sq1:    { name: 'Square-1',                            format: 'Average', cellname: 'Square-1' }
      clock:  { name: 'Rubik''s Clock',                      format: 'Average', cellname: 'Rubik''s Clock' }
      skewb:  { name: 'Skewb',                               format: 'Average', cellname: 'Skewb' }
      666:    { name: '6x6 Cube',                            format: 'Average', cellname: '6x6 Cube' }
      777:    { name: '7x7 Cube',                            format: 'Average', cellname: '7x7 Cube' }
      444bf:  { name: '4x4 Cube: Blindfolded',               format: 'Single',  cellname: '4x4 Blindfolded' }
      555bf:  { name: '5x5 Cube: Blindfolded',               format: 'Single',  cellname: '5x5 Blindfolded' }
      333mbf: { name: 'Rubik''s Cube: Multiple Blindfolded', format: 'Single',  cellname: '3x3 Multi Blind' }
      magic:  { name: 'Rubik''s Magic',                      format: 'Average', cellname: 'Rubik''s Magic' }
      mmagic: { name: 'Master Magic',                        format: 'Average', cellname: 'Master Magic' }

    abolition:
      - magic
      - mmagic

    single:
      - 444bf
      - 555bf
      - 333mbf

  country:
    id:
      'Afghanistan':            { id: 'Afghanistan',            continent: 'Asia',          record: 'AsR'}
      'Albania':                { id: 'Albania',                continent: 'Europe',        record: 'ER' }
      'Algeria':                { id: 'Algeria',                continent: 'Africa',        record: 'AfR'}
      'Argentina':              { id: 'Argentina',              continent: 'South America', record: 'SAR'}
      'Armenia':                { id: 'Armenia',                continent: 'Asia',          record: 'AsR'}
      'Aruba':                  { id: 'Aruba',                  continent: 'South America', record: 'SAR'}
      'Australia':              { id: 'Australia',              continent: 'Oceania',       record: 'OcR'}
      'Austria':                { id: 'Austria',                continent: 'Europe',        record: 'ER' }
      'Azerbaijan':             { id: 'Azerbaijan',             continent: 'Europe',        record: 'ER' }
      'Bangladesh':             { id: 'Bangladesh',             continent: 'Asia',          record: 'AsR'}
      'Belarus':                { id: 'Belarus',                continent: 'Europe',        record: 'ER' }
      'Belgium':                { id: 'Belgium',                continent: 'Europe',        record: 'ER' }
      'Belize':                 { id: 'Belize',                 continent: 'North America', record: 'NAR'}
      'Bolivia':                { id: 'Bolivia',                continent: 'South America', record: 'SAR'}
      'Bosnia and Herzegovina': { id: 'Bosnia and Herzegovina', continent: 'Europe',        record: 'ER' }
      'Brazil':                 { id: 'Brazil',                 continent: 'South America', record: 'SAR'}
      'Bulgaria':               { id: 'Bulgaria',               continent: 'Europe',        record: 'ER' }
      'Canada':                 { id: 'Canada',                 continent: 'North America', record: 'NAR'}
      'Chile':                  { id: 'Chile',                  continent: 'South America', record: 'SAR'}
      'China':                  { id: 'China',                  continent: 'Asia',          record: 'AsR'}
      'Colombia':               { id: 'Colombia',               continent: 'South America', record: 'SAR'}
      'Costa Rica':             { id: 'Costa Rica',             continent: 'North America', record: 'NAR'}
      "Cote d'Ivoire":          { id: 'Cote d_Ivoire',          continent: 'Africa',        record: 'AfR'}
      'Croatia':                { id: 'Croatia',                continent: 'Europe',        record: 'ER' }
      'Cuba':                   { id: 'Cuba',                   continent: 'North America', record: 'NAR'}
      'Cyprus':                 { id: 'Cyprus',                 continent: 'Europe',        record: 'ER' }
      'Czech Republic':         { id: 'Czech Republic',         continent: 'Europe',        record: 'ER' }
      'Denmark':                { id: 'Denmark',                continent: 'Europe',        record: 'ER' }
      'Dominican Republic':     { id: 'Dominican Republic',     continent: 'North America', record: 'NAR'}
      'Egypt':                  { id: 'Egypt',                  continent: 'Africa',        record: 'AfR'}
      'El Salvador':            { id: 'El Salvador',            continent: 'North America', record: 'NAR'}
      'Estonia':                { id: 'Estonia',                continent: 'Europe',        record: 'ER' }
      'Finland':                { id: 'Finland',                continent: 'Europe',        record: 'ER' }
      'France':                 { id: 'France',                 continent: 'Europe',        record: 'ER' }
      'Georgia':                { id: 'Georgia',                continent: 'Europe',        record: 'ER' }
      'Germany':                { id: 'Germany',                continent: 'Europe',        record: 'ER' }
      'Greece':                 { id: 'Greece',                 continent: 'Europe',        record: 'ER' }
      'Guatemala':              { id: 'Guatemala',              continent: 'North America', record: 'NAR'}
      'Hong Kong':              { id: 'Hong Kong',              continent: 'Asia',          record: 'AsR'}
      'Hungary':                { id: 'Hungary',                continent: 'Europe',        record: 'ER' }
      'Iceland':                { id: 'Iceland',                continent: 'Europe',        record: 'ER' }
      'India':                  { id: 'India',                  continent: 'Asia',          record: 'AsR'}
      'Indonesia':              { id: 'Indonesia',              continent: 'Asia',          record: 'AsR'}
      'Iran':                   { id: 'Iran',                   continent: 'Asia',          record: 'AsR'}
      'Ireland':                { id: 'Ireland',                continent: 'Europe',        record: 'ER' }
      'Israel':                 { id: 'Israel',                 continent: 'Europe',        record: 'ER' }
      'Italy':                  { id: 'Italy',                  continent: 'Europe',        record: 'ER' }
      'Japan':                  { id: 'Japan',                  continent: 'Asia',          record: 'AsR'}
      'Jordan':                 { id: 'Jordan',                 continent: 'Asia',          record: 'AsR'}
      'Kazakhstan':             { id: 'Kazakhstan',             continent: 'Asia',          record: 'AsR'}
      'Korea':                  { id: 'Korea',                  continent: 'Asia',          record: 'AsR'}
      'Kosovo':                 { id: 'Kosovo',                 continent: 'Europe',        record: 'ER' }
      'Latvia':                 { id: 'Latvia',                 continent: 'Europe',        record: 'ER' }
      'Lebanon':                { id: 'Lebanon',                continent: 'Asia',          record: 'AsR'}
      'Lithuania':              { id: 'Lithuania',              continent: 'Europe',        record: 'ER' }
      'Luxembourg':             { id: 'Luxembourg',             continent: 'Europe',        record: 'ER' }
      'Macau':                  { id: 'Macau',                  continent: 'Asia',          record: 'AsR'}
      'Macedonia':              { id: 'Macedonia',              continent: 'Europe',        record: 'ER' }
      'Malaysia':               { id: 'Malaysia',               continent: 'Asia',          record: 'AsR'}
      'Mauritius':              { id: 'Mauritius',              continent: 'Africa',        record: 'AfR'}
      'Mexico':                 { id: 'Mexico',                 continent: 'North America', record: 'NAR'}
      'Moldova':                { id: 'Moldova',                continent: 'Europe',        record: 'ER' }
      'Mongolia':               { id: 'Mongolia',               continent: 'Asia',          record: 'AsR'}
      'Montenegro':             { id: 'Montenegro',             continent: 'Europe',        record: 'ER' }
      'Morocco':                { id: 'Morocco',                continent: 'Africa',        record: 'AfR'}
      'Netherlands':            { id: 'Netherlands',            continent: 'Europe',        record: 'ER' }
      'New Zealand':            { id: 'New Zealand',            continent: 'Oceania',       record: 'OcR'}
      'Nigeria':                { id: 'Nigeria',                continent: 'Africa',        record: 'AfR'}
      'Norway':                 { id: 'Norway',                 continent: 'Europe',        record: 'ER' }
      'Pakistan':               { id: 'Pakistan',               continent: 'Asia',          record: 'AsR'}
      'Paraguay':               { id: 'Paraguay',               continent: 'South America', record: 'SAR'}
      'Peru':                   { id: 'Peru',                   continent: 'South America', record: 'SAR'}
      'Philippines':            { id: 'Philippines',            continent: 'Asia',          record: 'AsR'}
      'Poland':                 { id: 'Poland',                 continent: 'Europe',        record: 'ER' }
      'Portugal':               { id: 'Portugal',               continent: 'Europe',        record: 'ER' }
      'Puerto Rico':            { id: 'Puerto Rico',            continent: 'North America', record: 'NAR'}
      'Romania':                { id: 'Romania',                continent: 'Europe',        record: 'ER' }
      'Russia':                 { id: 'Russia',                 continent: 'Europe',        record: 'ER' }
      'Saudi Arabia':           { id: 'Saudi Arabia',           continent: 'Asia',          record: 'AsR'}
      'Serbia':                 { id: 'Serbia',                 continent: 'Europe',        record: 'ER' }
      'Singapore':              { id: 'Singapore',              continent: 'Asia',          record: 'AsR'}
      'Slovakia':               { id: 'Slovakia',               continent: 'Europe',        record: 'ER' }
      'Slovenia':               { id: 'Slovenia',               continent: 'Europe',        record: 'ER' }
      'South Africa':           { id: 'South Africa',           continent: 'Africa',        record: 'AfR'}
      'Spain':                  { id: 'Spain',                  continent: 'Europe',        record: 'ER' }
      'Sri Lanka':              { id: 'Sri Lanka',              continent: 'Asia',          record: 'AsR'}
      'Sweden':                 { id: 'Sweden',                 continent: 'Europe',        record: 'ER' }
      'Switzerland':            { id: 'Switzerland',            continent: 'Europe',        record: 'ER' }
      'Taiwan':                 { id: 'Taiwan',                 continent: 'Asia',          record: 'AsR'}
      'Thailand':               { id: 'Thailand',               continent: 'Asia',          record: 'AsR'}
      'Trinidad and Tobago':    { id: 'Trinidad and Tobago',    continent: 'South America', record: 'SAR'}
      'Tunisia':                { id: 'Tunisia',                continent: 'Africa',        record: 'AfR'}
      'Turkey':                 { id: 'Turkey',                 continent: 'Europe',        record: 'ER' }
      'Ukraine':                { id: 'Ukraine',                continent: 'Europe',        record: 'ER' }
      'United Arab Emirates':   { id: 'United Arab Emirates',   continent: 'Asia',          record: 'AsR'}
      'United Kingdom':         { id: 'United Kingdom',         continent: 'Europe',        record: 'ER' }
      'Uruguay':                { id: 'Uruguay',                continent: 'South America', record: 'SAR'}
      'USA':                    { id: 'USA',                    continent: 'North America', record: 'NAR'}
      'Venezuela':              { id: 'Venezuela',              continent: 'South America', record: 'SAR'}
      'Vietnam':                { id: 'Vietnam',                continent: 'Asia',          record: 'AsR'}
      'Yugoslavia':             { id: 'Yugoslavia',             continent: 'Europe',        record: 'ER' }

  continent:
    id:
      'Africa':
        - 'Algeria'
        - "Cote d'Ivoire"
        - 'Egypt'
        - 'Mauritius'
        - 'Morocco'
        - 'Nigeria'
        - 'South Africa'
        - 'Tunisia'
      'Asia':
        - 'Afghanistan'
        - 'Armenia'
        - 'Bangladesh'
        - 'China'
        - 'Hong Kong'
        - 'India'
        - 'Indonesia'
        - 'Iran'
        - 'Japan'
        - 'Jordan'
        - 'Kazakhstan'
        - 'Korea'
        - 'Lebanon'
        - 'Macau'
        - 'Malaysia'
        - 'Mongolia'
        - 'Pakistan'
        - 'Philippines'
        - 'Saudi Arabia'
        - 'Singapore'
        - 'Sri Lanka'
        - 'Taiwan'
        - 'Thailand'
        - 'United Arab Emirates'
        - 'Vietnam'
      'Oceania':
        - 'Australia'
        - 'New Zealand'
      'Europe':
        - 'Albania'
        - 'Aruba'
        - 'Austria'
        - 'Azerbaijan'
        - 'Belarus'
        - 'Belgium'
        - 'Bulgaria'
        - 'Bosnia and Herzegovina'
        - 'Croatia'
        - 'Cyprus'
        - 'Czech Republic'
        - 'Denmark'
        - 'Estonia'
        - 'Finland'
        - 'France'
        - 'Georgia'
        - 'Germany'
        - 'Greece'
        - 'Hungary'
        - 'Iceland'
        - 'Ireland'
        - 'Israel'
        - 'Italy'
        - 'Kosovo'
        - 'Latvia'
        - 'Lithuania'
        - 'Luxembourg'
        - 'Macedonia'
        - 'Moldova'
        - 'Montenegro'
        - 'Netherlands'
        - 'Norway'
        - 'Poland'
        - 'Portugal'
        - 'Romania'
        - 'Russia'
        - 'Serbia'
        - 'Slovakia'
        - 'Slovenia'
        - 'Spain'
        - 'Sweden'
        - 'Switzerland'
        - 'Turkey'
        - 'Ukraine'
        - 'United Kingdom'
        - 'Yugoslavia'
      'North America':
        - 'Belize'
        - 'Canada'
        - 'Costa Rica'
        - 'Cuba'
        - 'Dominican Republic'
        - 'El Salvador'
        - 'Guatemala'
        - 'Mexico'
        - 'Puerto Rico'
        - 'USA'
      'South America':
        - 'Argentina'
        - 'Azerbaijan'
        - 'Bolivia'
        - 'Brazil'
        - 'Chile'
        - 'Colombia'
        - 'Paraguay'
        - 'Peru'
        - 'Trinidad and Tobago'
        - 'Uruguay'
        - 'Venezuela'
