# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:         iWCA
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    [jquery-1.8.2.min.js, jquery.mobile-1.2.0.min.js, changeFormAction.js, disableAverageButton.js]

  has_layout:     true
  layout:         layout
